version: '3.0'

services:
  main_account_think:
    container_name: main_account_think
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 7070:7070
    command: >
      sh -c "NODE_ENV=development npx sequelize-cli db:migrate &&
             npm run start:dev"
    depends_on:
      - postgres
    restart: always

  postgres:
   container_name: postgres_account_think # Лучше дать уникальное имя, чтобы не путать
   image: postgres:14
   environment:
     - POSTGRES_PASSWORD=RfhbvFkm-Ithba
     - POSTGRES_USER=accountthink
     - POSTGRES_DB=accountthink
   ports:
     - "5433:5432"  # <--- ИЗМЕНЕНИЕ ЗДЕСЬ: Внешний порт 5433
   volumes:
     - pgdata:/var/lib/postgresql/data
   restart: always

volumes:
 pgdata: